# Generated by Django 6.1.1 on 2026-10-03 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_level', models.CharField(choices=[('Gampang', 'Easy'), ('Normal', 'Moderate'), ('Menantang', 'Challenging'), ('Expert', 'Expert')], default='Gampang', max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('indonesian_weekday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indonesian_weekend_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_weekday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_weekend_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_level', models.CharField(choices=[('siaga', 'Siaga'), ('waspada', 'Waspada'), ('awas', 'Awas')], default='siaga', max_length=20)),
                ('main_image', models.ImageField(max_length=255, upload_to='mountain_images/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_volcanic_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'mountains',
            },
        ),
        migrations.CreateModel(
            name='MountainPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to='mountain_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
                ('mountain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='mountain.mountain')),
            ],
            options={
                'db_table': 'mountain_pictures',
            },
        ),
    ]
