# Generated by Django 6.1.1 on 2026-10-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MountainPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='mountain_pictures/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mountain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=10)),
                ('difficulty_level', models.CharField(max_length=50)),
                ('region', models.CharField(max_length=100)),
                ('indonesian_weekday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('indonesian_weekend_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_weekday_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('international_weekend_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('alert_level', models.CharField(choices=[('siaga', 'SIAGA'), ('waspada', 'WASPADA'), ('awas', 'AWAS')], default='siaga', max_length=10)),
                ('main_image', models.ImageField(upload_to='mountain_images/')),
                ('is_favorite', models.BooleanField(default=False)),
                ('is_volcanic_active', models.BooleanField(default=False)),
                ('pictures', models.ManyToManyField(related_name='mountains', to='mountain.mountainpicture')),
            ],
        ),
    ]
