# Generated by Django 6.1.1 on 2026-10-03 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('identity_number', models.CharField(max_length=16)),
                ('phone_number', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=100)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('capability_level', models.CharField(choices=[('Pemula', 'Beginner'), ('Berpengalaman', 'Intermediate'), ('Advanced', 'Advanced')], default='Pemula', max_length=20)),
                ('medical_notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'hikers',
            },
        ),
    ]
